### ISSUE TITLE
标点工具console log有报错 鼠标移上去没反应

### ISSUE THREAD

**Issue by nealchen-cn** [Souma-Sumire/ff14-overlay-vite#3]
![image](https://user-images.githubusercontent.com/87366195/218755506-42f3cbd1-d8e3-4195-b50a-f3b1d3d1963c.png)

**Comment by nealchen-cn** [comment]
我试了下清理了localstore 可以了 谢谢

**Comment by Souma-Sumire** [comment]
localStorage？
