### ISSUE TITLE
关于obs自动录制悬浮窗没有工作

### ISSUE THREAD

**Issue by MinakawaYuki** [Souma-Sumire/ff14-overlay-vite#4]
国际服客户端，obs studio 29.0.2，呆萌act 均以管理员模式启动并添加防火墙白名单
输入obswebsocket的链接地址和密码之后显示连接成功，但是倒数之后不会自动录制，直接点击录制按钮是可以正常录制的，请问是什么原因？

**Comment by Souma-Sumire** [comment]
不知道，发报错信息

**Comment by Souma-Sumire** [comment]
直接QQ私聊我。

**Comment by Souma-Sumire** [comment]
你是否错误的勾选了WS支持

**Comment by Souma-Sumire** [comment]
我不知道为什么，ACT是否正常接受日志

**Comment by MinakawaYuki** [comment]
> 我不知道为什么，ACT是否正常接受日志

昨晚休息了没回复。act应该是正常的，我看过生成的log文件，也记录了倒计时的信息，因为整个流程没有出现报错的情况，单独的手动开启录制也是没问题的，所以我怀疑是不是悬浮窗没有读取到对应的act记录？(现在在上班，详细的只能晚上回家弄了

**Comment by Souma-Sumire** [comment]
手动点击悬浮窗的录制按钮，如果可以录制则clone项目本地部署测试一下到底哪里出了问题。如果不可以录制则是OBS的WS客户端问题。

**Comment by MinakawaYuki** [comment]
> 手动点击悬浮窗的录制按钮，如果可以录制则clone项目本地部署测试一下到底哪里出了问题。如果不可以录制则是OBS的WS客户端问题。

![image](https://user-images.githubusercontent.com/38065606/223413777-f2a5c416-d342-4229-b2fd-69a10a0fe344.png)
会不会是这个原因(

**Comment by Souma-Sumire** [comment]
是奥~

**Comment by MinakawaYuki** [comment]
呃啊 请问这个有解决方案么

**Comment by Souma-Sumire** [comment]
尝试重装Cactbot插件、Overlay插件。无效则重装全新ACT。

**Comment by MinakawaYuki** [comment]
好像是cactbot的问题，现在已经可以用了，辛苦了~多谢解答
